### ISSUE TITLE
Add endpoints to manage profile item list entries

### ISSUE THREAD

**Issue by cdriehuys** [knowmetools/km-api#112]
We need an endpoint to manage the entries in a list-type profile item. There should be an endpoint at `/know-me/items/<pk>/list-entries/` that handles listing and creating list entries. There should also be an endpoint at `/know-me/list-entries/<pk>/` that allows for updating and deleting specific entries.

We will have to add some sort of validation to the list entry creation to ensure that the profile item is allowed to have list entries.

**Comment by audsc** [comment]
Does this just need to be added to urls.py , or added/updated in other places as well?

**Comment by cdriehuys** [comment]
We would need `ListEntriesListVIew` to handle listing and creating entries, and `ListEntryDetailView` to handle updating/deleting of specific entries.

**Comment by audsc** [comment]
That makes sense, thanks!
