### ISSUE TITLE
Add 'share' method to KMUser model

### ISSUE THREAD

**Issue by cdriehuys** [knowmetools/km-api#131]
This method would give the user with the provided email address the specified access. The method's signature could look something like:
```python
share(self, email, can_read_all=False, can_write_all=False)
```

One question we need to answer is if there is already a `KMUserAccess` instance for the user, what should the behavior be?

**Comment by cdriehuys** [comment]
If there is no user with the provided email address, a pending user should be created using the method from #136.

**Comment by cdriehuys** [comment]
Since we aren't supporting sharing of individual profiles, the signature should become:
```python
share(email, can_write=False, has_private_profile_access=False)
```

**Comment by audsc** [comment]
We are thinking `share(email, isAdmin=False)` (see issue #157 ).

**Comment by cdriehuys** [comment]
We can discuss the signature more later once #157 is resolved.

**Comment by cdriehuys** [comment]
Since we have finalized the fields for the `KMUserAccessor` model, the signature will look like the one in my [previous comment](https://github.com/knowmetools/km-api/issues/131#issuecomment-321858009).
