### ISSUE TITLE
Add serializer for KMUserAccess model

### ISSUE THREAD

**Issue by cdriehuys** [knowmetools/km-api#134]
The serializer's `create` method should be overridden to use the `KMUser.share` method from #131.

**Comment by audsc** [comment]
Is this still blocked by #131?

**Comment by cdriehuys** [comment]
The serializer also shouldn't allow updates to the provided email address. There are two ways of approaching this:

##### CUSTOM VALIDATION

We override `validate_email` on the serializer to not allow changes to the email address unless a new instance is being created.

##### MULTIPLE SERIALIZERS

We have a serializer used for listing and creating accessors that has a read/write email field. We would also have a serializer used for updating accessors that has a read only email field.

**Comment by audsc** [comment]
The second option sounds more like what we have been doing, is that an inaccurate assessment?

**Comment by cdriehuys** [comment]
The multiple serializer option is usually used when the fields differ between the list and detail views. In this case we are modifying attributes of a particular field, so it might be overkill to create separate serializers.

I think that since we don't anticipate displaying different fields for the list vs detail views, a single serializer with additional validation would be our best bet.

**Comment by audsc** [comment]
I am working on a single serializer with additional validation.
