### ISSUE TITLE
Add ability to mark profiles as public

### ISSUE THREAD

**Issue by cdriehuys** [knowmetools/km-api#154]
### Feature Proposal

As we discussed, it is easier from a user perspective to restrict access to specific profiles rather than on a per-user basis. To accomplish this, we would need to add a field to mark profiles as public, and a field to the Know Me user accessors that allows access to private profiles.

This will also allow us to remove the `KMUserAccessor.can_read_everywhere` field since the presence of an accessor implies read access to all public profiles.

**Comment by audsc** [comment]
Does adding a`public_profile` boolean to the profile make sense?

**Comment by Brandogs** [comment]
lets make this field `is_private`

**Comment by audsc** [comment]
In our previous access model, from my understanding, all information about access was contained in the `KMUserAccessor` and `ProfileAccessor`. Adding this field moves some of that information to the `Profile` model. Is this what we want, or is it better to keep access information separated from the models?

**Comment by cdriehuys** [comment]
Since `KMUserAccessor` holds access information for a specific user, it doesn't make sense for it to contain the private/public state of the profile since that applies to all access.
