### ISSUE TITLE
Add method to get the profiles accessible to a user

### ISSUE THREAD

**Issue by cdriehuys** [knowmetools/km-api#155]
### Feature Proposal

The `Profile` model should have a method that returns all the profiles that the provided user has access to. Something like:
```python
get_profiles_for_user(user)
```

**Comment by audsc** [comment]
Should this method return the profiles that a user has `write` access to?

**Comment by cdriehuys** [comment]
It should return all the profiles that the user has `read` access to.

**Comment by audsc** [comment]
If this method is created in the `Profile` model, is it checking whether a user has access to a singular profile? (It could be called somewhere else on all of the profiles to return the list).

**Comment by cdriehuys** [comment]
The way I initially envisioned was something like:
```python
class Profile:
    @classmethod
    def get_profiles_for_user(cls, user):
        return cls.objects.filter(foo=bar)    # some logic to get the appropriate profiles
```

**Comment by audsc** [comment]
Oh cool, that makes more sense I think.

**Comment by cdriehuys** [comment]
Is this method even needed? As long as we change the filter backends (#173) I can't think of a use for this method.

**Comment by cdriehuys** [comment]
The main use of this method was going to be for the filter backends. However, we removed the duplicated code which would have made this method useful.
