### ISSUE TITLE
Update filter backends to respect sharing

### ISSUE THREAD

**Issue by cdriehuys** [knowmetools/km-api#173]
### Feature Proposal

The filter backends for Know Me currently return items owned by the requesting user. They should be updated to also return items that the requesting user is granted access to through a `KMUserAccessor`.

**Comment by audsc** [comment]
@cdriehuys I'm not sure how to do this, would appreciate some pointers.

**Comment by cdriehuys** [comment]
I'll try to implement one of the filters and you can use that as a starting point.

**Comment by cdriehuys** [comment]
@audsc See #181 for an idea of how to accomplish this.
