### ISSUE TITLE
Add categories for media resources

### ISSUE THREAD

**Issue by cdriehuys** [knowmetools/km-api#212]
### Feature Proposal

Media resources should be able to be categorized. In practice this will end up creating a structure where media resources can be in the root "folder" or in a single-level-deep "folder".

For example:

```
Media Resources:
├── Category 1
│   ├── Resource 1
│   └── Resource 2
├── Category 2
│   └── Resource 3
├── Resource 4
└── Resource 5
```

#### Model Details

Categories only need an owner (Know Me user) and a name.

**Comment by cdriehuys** [comment]
@Brandogs Does this still match up with what we're thinking for the bookshelf view?

**Comment by Brandogs** [comment]
@cdriehuys No, the current requirements have removed the need for categories, removing the single-level "folder"
