### ISSUE TITLE
Manually Sorted Bookshelf

### ISSUE THREAD

**Issue by Brandogs** [knowmetools/km-api#232]
### Feature Proposal

All bookshelf resources should be manually sortable. The bookshelf should keep track of if the admin wants the bookshelf to appear in the manual, alphabetical, reverse alphabetical order for all other users.

**Comment by cdriehuys** [comment]
We're placing this on hold until we can discuss the reasoning behind this. It seems like there is a better way to accomplish the end goal of manual sorting.

**Comment by cdriehuys** [comment]
@Brandogs, any updates on this?

**Comment by Brandogs** [comment]
@cdriehuys Susan is currently using Alex's profile to think about the different scenarios on how Bookshelf could be used. We should hopefully have a decision on if we will go forward with this change this week.

**Comment by cdriehuys** [comment]
Closing this for now so we don't have to track it. If we decide to implement this moving forward, we will reopen it.
