### ISSUE TITLE
Minimum iOS Client version

### ISSUE THREAD

**Issue by Brandogs** [knowmetools/km-api#233]
### Feature Proposal

The iOS version of the app needs to be able to check with the database to see the the minimum required version of the app so it can know when to prompt users to update if necessary.

**Comment by cdriehuys** [comment]
So my understanding of this is that we need an endpoint like `/versions/` that simple returns the lowest usable version of the iOS application.

**Comment by Brandogs** [comment]
Yep, that would be perfect.

**Comment by cdriehuys** [comment]
The endpoint is available at `/know-me/config/`, and it can contain more information in the future if we need.
