### ISSUE TITLE
Update Timestamps

### ISSUE THREAD

**Issue by Brandogs** [knowmetools/km-api#235]
An update timestamp needs to be added to all profile, bookshelf, and journal tables in the database and returned through the api to improve the syncing logic when a user has been working offline.

**Comment by cdriehuys** [comment]
@Brandogs, do you just need a last-updated timestamp, or would a creation timestamp be helpful as well?

**Comment by Brandogs** [comment]
@cdriehuys I think that a creation timestamp could also be useful in the future, so let's go ahead with both
