### ISSUE TITLE
Add profile image for users

### ISSUE THREAD

**Issue by Brandogs** [knowmetools/km-api#259]
The users first run requirements have changed to include the ability to give users the option to upload their hero image when creating the account. This means we will need to create user details at the time of signup, prior to an email account being confirmed. 

The user details name can be pulled from the first name field of the user, but we will also need to be able to provide the hero image at signup. The quote will not be included as part of the signup process.

**Comment by cdriehuys** [comment]
Is this signup for a Know Me (company) account, or signup for a Know Me (app) account. For example, if we migrate Friends over, is it the same hero image?

**Comment by Brandogs** [comment]
Right now, this is just app level. Friends doesn't have anything like user images since there isn't any concept of following in Friends. However, this is a good thing to consider, as we haven't talked about this potential for other future apps, or possibly changing that if and when Friends is migrated. I'll bring this up during our meeting tomorrow and let you know.

**Comment by cdriehuys** [comment]
The real question that I need answered in order to implement this is do users who only follow other users (ie don't have their own profile) need to be able to have a hero image?

**Comment by cdriehuys** [comment]
The real requirement here is that users be able to upload a profile image when they create their account. This image should be optional.
