### ISSUE TITLE
How do we want to handle the "hero" image for Know Me users

### ISSUE THREAD

**Issue by cdriehuys** [knowmetools/km-api#263]
We are adding profile images in #259 that represent the user across all Know Me products, but how does that tie into the hero image used for profiles? We discussed the possibility of defaulting the hero image to the account image, but we ran into the issues of what if the account image doesn't scale well to the size of the hero image, or what if a user doesn't want to use their account image. The best approach we came up with was giving the user 3 choices when creating their "Profile Account":

1. No hero image
2. Use the account image
3. Upload a new image

In the case of using the account image, that also raises the issue of what to do when the account image changes. Here we have 2 choices:

1. Once the user elects to use their account image as their hero image, we make a copy of the image. Changing the account image would have no effect on the hero image.
2. The account image is a fallback for the hero image. If there is no hero image, we fall back to the user's current account photo.

@Brandogs, let me know what you think, or if we've come to any further conclusions here.

**Comment by Brandogs** [comment]
@cdriehuys Susan and I discussed this a few minutes ago and neither of us have a strong opinion on this. Unless you strongly feel one way or the other, we should just go with what is simplest.

**Comment by cdriehuys** [comment]
I decided to implement it so that the Know Me user inherits the user's profile image at the time of creation. It can be changed independently of the profile image at any time.
