### ISSUE TITLE
Create KMUser during Sign Up

### ISSUE THREAD

**Issue by Brandogs** [knowmetools/km-api#277]
When creating an account for a new User, we should also automatically create the KMUser for this individual. Their first name and the option account image should be used for the KMUser's name and hero image. As a result, we should also remove the ability to post to the Users endpoint because all users will already have a KMUser created if they have an account.

**Comment by cdriehuys** [comment]
The main reason to implement this is to eliminate a bunch of edge cases on the frontend.
