### ISSUE TITLE
No response from server for GET and POST until after timeout or connection ends

### ISSUE THREAD

**Issue by Brandogs** [knowmetools/km-api#298]
GET and POST is not executing until after the connection has timed out or been terminated.

It looks like this is being caused by the addition of Raven Python, which was added in the same commit as CORS:
'raven.contrib.django.raven_compat'

**Comment by cdriehuys** [comment]
Wow. I hadn't even considered that. I'll look into it.

**Comment by cdriehuys** [comment]
@Brandogs Does this issue occur for all versions of raven? Prior to the breaking commit we used version `6.3.0`. We are now up to `6.6.0`. If you could test versions `6.3.0`, `6.4.0`, and `6.5.0` that would be great.

**Comment by Brandogs** [comment]
Versions `6.2.0` through `6.6.0` all have this same issue. `6.1.0` is working.

**Comment by cdriehuys** [comment]
To verify, if you checkout the `hotfix/v0.8.1` branch, the issue is resolved?

You will probably have to delete your local version of the branch first since I overwrote some changes on it.

**Comment by Brandogs** [comment]
Yeah, the server is responding now as it use to. Seems like this version of Raven my be having some issues behind the scenes though:

> AttributeError("'URLResolver' object has no attribute 'regex'",)
> Traceback (most recent call last):
>   File "/Users/brandongsmith/.virtualenvs/km-api-hotfix/lib/python3.4/site-packages/raven/contrib/django/middleware/__init__.py", line 100, in process_view
>     client.get_transaction_from_request(request)
>   File "/Users/brandongsmith/.virtualenvs/km-api-hotfix/lib/python3.4/site-packages/raven/contrib/django/client.py", line 304, in get_transaction_from_request
>     return self.resolver.resolve(request.path)
>   File "/Users/brandongsmith/.virtualenvs/km-api-hotfix/lib/python3.4/site-packages/raven/contrib/django/resolver.py", line 88, in resolve
>     match = self._resolve(resolver, path)
>   File "/Users/brandongsmith/.virtualenvs/km-api-hotfix/lib/python3.4/site-packages/raven/contrib/django/resolver.py", line 53, in _resolve
>     match = resolver.regex.search(path)
> AttributeError: 'URLResolver' object has no attribute 'regex'

**Comment by cdriehuys** [comment]
The changes that have been added since 6.1.0 have added support for Django 2. Can you go back to raven 6.6.0 and add the following to `settings.py`?

```
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'raven': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}
```

Now if you run `manage.py runserver`, do you see any useful information from the endpoints that are timing out?

**Comment by Brandogs** [comment]
No, this just returns it to the previous behavior where it times out client side, and then shows 200 return codes in the terminal for all the requests.

**Comment by cdriehuys** [comment]
When you get a chance can you set up [the test project](https://github.com/knowmetools/django-raven-tests) and see if you can hit the endpoint from iOS?

**Comment by Brandogs** [comment]
The test project has the same behavior as our actual project. Nothing happens until timeout or the app is killed. Then the API shows the request was a success with no other detail.

> [26/Mar/2018 15:22:50] "GET /my-app/foo/ HTTP/1.1" 200 18

**Comment by Brandogs** [comment]
The hanging behavior in Raven 6.2.0 and higher occurs when an empty set of parameters are provided for the http body.

```
func request(parameters: [String:Any] = [:]) {
     ...
     request.httpBody = try? JSONSerialization.data(withJSONObject: parameters)
     ...
}
```

We can account for this variation in behavior with Raven on the front end by checking parameters.count before setting the http body.

**Comment by cdriehuys** [comment]
So to be clear, it hangs when a body (even if empty) is provided to an endpoint that doesn't expect it?

**Comment by Brandogs** [comment]
Good catch on the clarification. I didn't initially test that, but that seems to be the case. I just ran the following code and hit the same hanging issue for endpoints with no parameters:

```
if parameters.count > 0 {
      request.httpBody = try? JSONSerialization.data(withJSONObject: parameters)
} else {
      request.httpBody = try? JSONSerialization.data(withJSONObject: ["hey":"hi"])
}
```
