### ISSUE TITLE
Investigate handling subscriptions through Apple

### ISSUE THREAD

**Issue by cdriehuys** [knowmetools/km-api#318]
### Feature Proposal

Since Apple requires any payments made on an iOS device to go through them, we must use their subscription system if we want to allow people to manage their subscriptions from within the app (which makes the most sense). [Apple's documentation on subscriptions](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/StoreKitGuide/Chapters/Subscriptions.html) lays out the process of handling subscriptions through webhooks.

The only way we would be able to avoid this is if we only allow people to manage payments on the web app, and that seems like a poor solution because Apple disallows us from referring people to the web app to pay from within our app.

**Comment by cdriehuys** [comment]
We need to answer the questions raised in #319 before we can dig into this.

**Comment by Brandogs** [comment]
Yeah, unfortunately we will need people to be able to subscribe through the app. I don't think there's much of a way around it.

**Comment by cdriehuys** [comment]
We are moving forward on providing subscriptions through Apple.
