### ISSUE TITLE
Pre-payment decisions

### ISSUE THREAD

**Issue by cdriehuys** [knowmetools/km-api#319]
Before we can start work on accepting payments, we need to nail down the features we need.

### Payment Type

I believe we're leaning towards a subscription model, but we need to make that choice for sure before we can continue.

- [x] Subscription
- [ ] One time payment

#### Subscription Length

If we go down the subscriptions path, are we going to just have a monthly plan, or will we offer a discounted(?) annual plan as well?

- [ ] Monthly only
- [x] Possibility for other plans

---

### Integration with Friends

Do we ever want to bundle Friends and Faces into this pricing system. It would be a whole lot easier to integrate them later if we do the work now.

- [ ] Possibility for integrating payments across apps
- [x] Separate systems

---

### Trials

Are we going to offer a trial of the paid version in addition to a free version?

- [x] Trial
- [ ] No trial

*Edit: Trials will be handled through Apple's subscription system.*

**Comment by bsuto** [comment]
I think we've for sure decided to go the subscription route, with a free trial. Currently, the "trial" is three months for this summer beta period. My proposal for the other questions here:
- Offer monthly and annual subscription options (e.g. $5.99/month and $59.99/year)
- Offer a two week free trial
- Separate payment system for Friends (proposal: free in App Store, free to use locally, implement similar but lower cost structure to add cloud sync – perhaps 99¢/month and $9.99/year)

**Comment by cdriehuys** [comment]
It seems that we have finalized our plans for subscriptions, so closing this discussion.
