### ISSUE TITLE
Journal search is inconsistent

### ISSUE THREAD

**Issue by Brandogs** [knowmetools/km-api#320]
### Bug Report

The journal search is working inconsistently. Most of the time it returns the expected results. However, I recently noticed certain queries are returning odd results.

You can use the following credentials to recreate the issue in Postman:
https://dev.toolbox.knowmetools.com/know-me/users/1/journal-entries/
Token f9d55cf58d5ee5f8417c335dd2e081f4e1766fef

A lot of queries are returning as expected. For example:
https://dev.toolbox.knowmetools.com/know-me/users/1/journal-entries/q=Tap
You can see ids 3-7 have been returned

However, for some reason this request loses ID #7 from the results:
https://dev.toolbox.knowmetools.com/know-me/users/1/journal-entries/?q=Tap%20h

Here are some other odd result sets:

Returns entries without 2 in it:
https://dev.toolbox.knowmetools.com/know-me/users/1/journal-entries/?q=2

Returns nothing, but should return ID #2, which starts with the word "this":
https://dev.toolbox.knowmetools.com/know-me/users/1/journal-entries/?q=this

**Comment by cdriehuys** [comment]
@Brandogs, feel free to re-open this if it is still an issue, but I am closing this for now.
