### ISSUE TITLE
User Result Order

### ISSUE THREAD

**Issue by Brandogs** [knowmetools/km-api#326]
Can we adjust the order of users to always return the active user's account first, followed by the other account they have access to?

https://dev.toolbox.knowmetools.com/know-me/users

**Comment by cdriehuys** [comment]
Would it be enough to indicate which user is owned by the active user? We could just add that property to the user serializer.

```js
[
  {
    "id": 1,
    ...
    "is_owner": false
  },
  {
    "id": 7,
    ...
    "is_owner": true
  }
]
```

**Comment by Brandogs** [comment]
That would helpful too, but I do think we want it sorted by is_owner as well so we get the logged in user first.
