### ISSUE TITLE
Accepted accessor list not returning correct results

### ISSUE THREAD

**Issue by cdriehuys** [knowmetools/km-api#351]
### Bug Report

From @Brandogs 

>The accepted accessor list doesn't seem to be working. It's only kicking back the currently logged in user for me. The user I'm messing with has access to two different user's profiles.

**Comment by cdriehuys** [comment]
I can't reproduced this issue, could you be more specific?

**Comment by Brandogs** [comment]
Take a look at this account:
Token f9d55cf58d5ee5f8417c335dd2e081f4e1766fef

The accepted accessor list only returns 1 account, which is the current user. However, the account has access to 3 different users.
https://dev.toolbox.knowmetools.com/know-me/accessors/accepted/
https://dev.toolbox.knowmetools.com/know-me/users/

**Comment by cdriehuys** [comment]
From what I've seen, that all looks correct. The account actually only has access to two users, the one owned by the user (ID 1), and one through an accessor (ID 3). There is a pending accessor granting access to another user (ID 5). It does look like 3 users though because of #352.

`/know-me/accessors/pending/` correctly lists the accessor for user 5 since it has not been accepted yet.

`/know-me/accessors/accepted/` correctly lists the accessor granting access to user 3 since it is the only accessor that has been accepted by user 1.


Based on this, I'm closing the issue. Feel free to reopen it if this behavior is still unexpected.

**Comment by Brandogs** [comment]
You are right. The detail on the return made me mistake what was going on. It's not an incorrect list but  the details return aren't what we need. I've raised the following issue: https://github.com/knowmetools/km-api/issues/354
