### ISSUE TITLE
Pending and Accepted Users Need Account Details

### ISSUE THREAD

**Issue by Brandogs** [knowmetools/km-api#354]
### Bug Report

Pending and Accepted Accessor lists return no detail about the actual account. It only shows detail about the user who is logged in. We need to display info about which account the user is accepting/declining or unfollowing.

**Comment by cdriehuys** [comment]
I agree with this. In addition to the information already present, would the following be enough?

```json
{
  "other": "accessor attributes",

  "km_user": {
    "id": 42,
    "name": "Douglas Adams",
    "image": "https://example.com/image.jpg"
  },

  "more": "accessor attributes"
}
```
