### ISSUE TITLE
Cannot Delete Others Comments in Journal

### ISSUE THREAD

**Issue by Brandogs** [knowmetools/km-api#371]
**Environment (production/development)**
Occurs in: Dev/Prod

**Describe the bug**
Trying to delete another users comment on your own Journal throws a 403 error. Admins should have the ability to delete, but not edit, other users comments in Journal.

**To Reproduce**
1. Invite User B to follow User A
2. Comment on User A's journal post as User B
3. Try to delete User B's journal comment as User A

**Expected behavior**
Comment should be deleted.

**Comment by cdriehuys** [comment]
This may be because the permissions system is not correctly mapping `DELETE` requests to the `destroy` permission. I'll investigate later.
