### ISSUE TITLE
Reset Password Not Sending Email

### ISSUE THREAD

**Issue by Brandogs** [knowmetools/km-api#390]
**Environment (production/development)**
Occurs in: Production  and Development

**Describe the bug**
When attempting to reset passwords for an unverified account, a password reset email is never sent. If a user has forgotten their password, there is no way to verify the account and get past this point.

**Comment by cdriehuys** [comment]
I have now successfully received password reset emails for both the staging and production environments. If you can still reproduce this issue, feel free to reopen it.

**Comment by cdriehuys** [comment]
Since that is the intended behavior of the current system, I am closing this issue and raising a new feature request in #393.
