### ISSUE TITLE
Transfer Subscription

### ISSUE THREAD

**Issue by Brandogs** [knowmetools/km-api#396]
In case use makes a purchase while logged in on the wrong Know Me account, an endpoint is required to allow a Know Me user to transfer their subscription to another valid, unsubscribed Know Me account.

**Comment by cdriehuys** [comment]
The simplest solution here is to just check if the provided transfer email is tied to a valid Know Me account that doesn't have premium yet. If it does, the transfer goes through. If it does not, an error message is returned.

*__Note:__ This solution leaks email addresses. First, transfer attempts give information as to whether an email is tied to a valid Know Me account. Second, if the transferer knows an email address is used, they can use the transfer functionality to determine if an account already has a premium subscription.*

**Comment by cdriehuys** [comment]
We have to be careful of how we overwrite existing `Subscription` instances. Consider the following scenario:

> Sally, a user, buys a premium subscription through the Apple store. After a few months, her payment method expires, and her subscription expires. During this lapse, Jim transfers his premium subscription to Sally.
>
> If Sally fixes her payment method with the Apple store, she will still be paying for the subscription that was replaced even though it is not used as Jim pays for her "active" subscription.

As a result, I don't believe we can transfer subscriptions if the recipient has any "subscription method" on file (currently the only possibility is an Apple receipt).

**Comment by cdriehuys** [comment]
As per our conversation, if the recipient has any Apple receipt data on file, an error should be returned indicating that the recipient must delete their Apple subscription before they can receive the transfer.
