### ISSUE TITLE
Unable to Reset Password

### ISSUE THREAD

**Issue by Brandogs** [knowmetools/km-api#436]
**Environment (production/development)**
Occurs in: PROD

**Describe the bug**
When attempting to reset a password for an account, an email is sent to the user.
When clicking on the link provided by the email, an "Access Denied" error is displayed in the browser.

<Error>
<Code>AccessDenied</Code>

<Message>Access Denied</Message>
<RequestId>7C64D349A584252F</RequestId>

<HostId>
R+z0BiYU3Mdr6hJKXc7Nh94GLplEEGaPFA2F6rKc5jdlemHlyplzmGXOSDcHGHFOroUyfXXhi/0=
</HostId>

</Error>

**Comment by cdriehuys** [comment]
This is not an issue with the API but rather an issue with the deployment process. See knowmetools/km-api-deployment#20 for details.
