### ISSUE TITLE
Subscription Expiration TS for Users Endpoint

### ISSUE THREAD

**Issue by Brandogs** [knowmetools/km-api#465]
Add the subscription expiration timestamp to the /know-me/users/ endpoint.

**Comment by cdriehuys** [comment]
This information is available from `/know-me/subscription/apple/` under the `expiration_time` key of the response. If the user does not have a subscription, a 404 response will be returned. Does this solve your intended use case?

**Comment by Brandogs** [comment]
Yeah, this will work for now. We still may want to add this in the future in case we implement payment methods outside of Apple.

**Comment by cdriehuys** [comment]
If we hoist the expiration time any higher, it would be to the `/know-me/subscription/` endpoint.
