### ISSUE TITLE
Receipt Hash Mismatched

### ISSUE THREAD

**Issue by Brandogs** [knowmetools/km-api#490]
**Environment (production/development)**
Occurs in: Dev

**Describe the bug**
When uploading a receipt, even after the iOS application has just refreshed the receipt, a different receipt is returned from the /subscription/apple/ endpoint and the two hash values between the client and api do not match.

**To Reproduce**
1. Request a receipt refresh from apple in the iOS client (happens automatically on load)
2. In requestDidFinish for the SKReceiptRefreshRequest, upload the receipt to the Know Me API to guarantee the latest version of the receipt has been uploaded.
3. Compare hash values for the API and the SKReceiptRefreshRequest.

**Expected behavior**
Has values should be the same, but receipt and hash values do not match

**Comment by cdriehuys** [comment]
Since comparison by hash does not seem to be working, we are going to overhaul the query process. See #497 for progress.
