### ISSUE TITLE
Cannot Transfer Subscription

### ISSUE THREAD

**Issue by Brandogs** [knowmetools/km-api#493]
**Environment (production/development)**
Occurs in: Dev

**Describe the bug**
Users receive the following error when attempting to transfer a subscription to a user without subscription data associated: "The intended recipient has an Apple subscription that must be removed before they can accept a transfer."

**To Reproduce**
1. User A and B subscribe
2. User B deletes the subscription data associated with their account
3. User A attempts to transfer their subscription to User B

**Expected behavior**
The subscription should be transferred to the other user.

**Comment by cdriehuys** [comment]
Can you be more explicit with the steps to reproduce the issue?

1. I'm assuming both users upload valid Apple receipts granting them Know Me premium.
2. Does user B send a `DELETE` request to `/know-me/subscription/apple/`?

**Comment by cdriehuys** [comment]
The issue here is with the following code block in `km_api/know_me/serializers/subscription_serializers.py`, which uses the wrong model (old one):

```
        if models.SubscriptionAppleData.objects.filter(
            subscription__user=self._recipient_email_inst.user
        ).exists():
            raise serializers.ValidationError(
                ugettext(
                    "The intended recipient has an Apple subscription that "
                    "must be removed before they can accept a transfer."
                )
            )
```
