### ISSUE TITLE
Fix contact info in emails

### ISSUE THREAD

**Issue by cdriehuys** [knowmetools/km-api#507]
**Environment (production/development)**
Occurs in: production

**Describe the bug**
All HTML emails sent from the app have incorrect contact information.

The email address is an old "knowmetools" domain and the phone number has a literal `&dash;` in it.

**Expected behavior**
The email should be switched to team@knowme.works and the phone number should read `(919) 960-1717`.

**Comment by bsuto** [comment]
the reply-to address on these emails is at the old domain too

**Comment by cdriehuys** [comment]
The reply-to is now tracked in #508. It's configured in a separate location so I split the issue.
