### ISSUE TITLE
Should tokens expire

### ISSUE THREAD

**Issue by cdriehuys** [knowmetools/km-api#57]
Token expiration would help mitigate the risks associated with logging in on a public computer and forgetting to log off. On the other hand, it would make client side logic more difficult because we would have to handle reissuing a token when nearing the expiration time.

**Comment by audsc** [comment]
Do you think public logins will be common? Maybe this would be a good question to ask the downstairs team. From my limited knowledge I would think that public computer logins would not be very common with our user base but I could be wrong.

**Comment by cdriehuys** [comment]
This is also not very important until we have a web app. The only reason for bringing it up now is to make it easier to build into the iOS app instead of adding it later.

**Comment by cdriehuys** [comment]
This seems like a non-issue for a while. If we do want to bring this up again, I would suggest looking at different websites' implementation of token expiration in relation to the type of data that they store.
