### ISSUE TITLE
Resending Verification Emails

### ISSUE THREAD

**Issue by Brandogs** [knowmetools/km-api#71]
There needs to be a way to request verification emails be sent again. This is particularly important since they expire.

**Comment by cdriehuys** [comment]
How should this be handled? My current thoughts are we should have an endpoint at `/account/resend-verification/`. The endpoint should accept a `POST` request containing an email address. If that email address is present in our database and marked as unauthenticated, a new verification should be sent out. If that email is not present in our database, the request should succeed, but not do anything.

I believe this process is similar to password resets in that we have to be careful to not expose which email addresses are present in our system.

**Comment by Brandogs** [comment]
I don't think we need to reset verified accounts as unauthenticated. The only time this would be called that I can think of would be if a user tried to log in and the account was not authenticated. If the user had already authenticated, the would be logged in instead of sending the resend request.
