### ISSUE TITLE
Should we automatically resend expired email verifications when a login is attempted

### ISSUE THREAD

**Issue by cdriehuys** [knowmetools/km-api#72]
If a user initiates the sign up process but never verifies their email, what should we do when they attempt to log in. As per #70, they will receive a message stating their email is unverified, but we could go a step further and automatically resend the verification email if the previous one has expired.

**Comment by audsc** [comment]
If the email was caught by their spam filter or some other filter, resending it won't do much good. I like the idea of resending the verification email but I'm not actually sure how useful it is in practice.

**Comment by cdriehuys** [comment]
I believe the initial idea behind this was to assist users who started the registration process and never got around to verifying their email.

The more I think about this however, the more I feel it's unneeded. I can't think of a single other service that automatically resends a verification email.

I do think we can make it easier for people to troubleshoot email verification by providing tips such as "check your spam folder" but I don't think this feature would add any value. Feel free to reopen if you feel otherwise.
