### ISSUE TITLE
Omit untested files from coverage report

### ISSUE THREAD

**Issue by cdriehuys** [knowmetools/km-api#77]
There are some files that we can't/don't want to test. These files should be excluded from the coverage report by adding them to the `omit` section of the `.coveragerc` file.

* **Migrations:** Since these files are autogenerated, we don't test them and they are artificially inflating our hit count. Exclude with the pattern `*/migrations/*`.
* **Admin Configuration:** We consider the admin site as a non-critical piece of the project, and it is tested extensively by the Django maintainers, so we don't need to test it. These files just add noise to the coverage report. Exclude with the pattern `*/admin.py`.
* **Settings:** I'm on the fence about everything in the `km_api/km_api` folder. We don't explicitly test anything in there, but I don't know if we should be.

**Comment by audsc** [comment]
We discussed and agreed to exclude settings from the coverage report.
