### ISSUE TITLE
Fix upload path for media resource items

### ISSUE THREAD

**Issue by cdriehuys** [knowmetools/km-api#88]
The `upload_to` function for `MediaResource` instances should be namespaced to the `know-me` folder, similar to the images for the `KMUser` model.

**Comment by cdriehuys** [comment]
This is blocked until #65 is completed.

**Comment by cdriehuys** [comment]
@audsc This can be worked on now that media resources are attached to a `KMUser`.

**Comment by audsc** [comment]
Should the file path be the same as that of the KMUser model to get rid of reference to gallery?
 So it would be : `know-me/users/{id}/images/{file}` .
